CREATE TABLE "user" (id BIGINT generated always as identity, email VARCHAR(50) NOT NULL, team_id BIGINT NOT NULL, password VARCHAR(60) NOT NULL, confirmed BOOLEAN, locked BOOLEAN, attempts SMALLINT, ip_address VARCHAR(47) NOT NULL, confirmation_uuid VARCHAR(36) NOT NULL);
CREATE TABLE "team" (id BIGINT NOT NULL PRIMARY KEY, team_name VARCHAR(128) NOT NULL);
CREATE TABLE "game" (id BIGINT NOT NULL PRIMARY KEY, "date" TIMESTAMP NOT NULL, game_state VARCHAR(20) NOT NULL, home_team_id BIGINT NOT NULL, away_team_id BIGINT NOT NULL, home_team_goals SMALLINT, away_team_goals SMALLINT);
CREATE TABLE "game_player" (id_game_id BIGINT NOT NULL, id_player_id BIGINT NOT NULL, team_id BIGINT NOT NULL, position VARCHAR(20) NOT NULL, "name" VARCHAR(256) NOT NULL, goals SMALLINT, assists SMALLINT, short_goals SMALLINT, short_assists SMALLINT, goals_against SMALLINT, time_on_ice VARCHAR(8),  PRIMARY KEY(id_game_id, id_player_id));
CREATE TABLE "pick" (id SERIAL PRIMARY KEY, group_id BIGINT, user_id BIGINT NOT NULL, game_id BIGINT NOT NULL, game_player_id_game_id BIGINT, game_player_id_player_id BIGINT, goalies BOOLEAN, team BOOLEAN, points SMALLINT);
ALTER TABLE "user" ADD COLUMN display_name VARCHAR(50);
ALTER TABLE "user" ADD COLUMN profile_pic bytea;
ALTER TABLE "pick" RENAME COLUMN team TO the_team;
ALTER TABLE "pick" ADD COLUMN team_id BIGINT;
CREATE TABLE "user_user" (id SERIAL PRIMARY KEY, from_user BIGINT NOT NULL, to_user BIGINT NOT NULL);
CREATE TABLE "user_team" (id SERIAL PRIMARY KEY, team_id BIGINT NOT NULL, user_id BIGINT NOT NULL);
ALTER TABLE "user" DROP COLUMN "team_id";
ALTER TABLE "pick" DROP COLUMN "group_id";
ALTER TABLE "user" ADD COLUMN reddit_username VARCHAR(40) NULL;
ALTER TABLE "team" ADD COLUMN abbreviation VARCHAR(8) NULL;
ALTER TABLE "team" ADD COLUMN short_name VARCHAR(32) NULL;
ALTER TABLE "user" ADD COLUMN admin BOOLEAN NULL;
CREATE TABLE "announcer" (id SERIAL PRIMARY KEY, team_id BIGINT NOT NULL, display_name VARCHAR(32) NOT NULL, nickname VARCHAR(32) NOT NULL);
INSERT INTO "announcer" (team_id, display_name, nickname) VALUES (17, 'Mickey Redmond', '#IMWITHMICK');
INSERT INTO "announcer" (team_id, display_name, nickname) VALUES (17, 'Larry Murphy', '#IMWITHMURPHY');
INSERT INTO "announcer" (team_id, display_name, nickname) VALUES (17, 'Chris Osgood', '#IMWITHOZZY');
INSERT INTO "announcer" (team_id, display_name, nickname) VALUES (17, 'Ken Daniels', '#IMWITHKEN');
INSERT INTO "announcer" (team_id, display_name, nickname) VALUES (17, 'Trevor Thompson', '#IMWITHTREV');
INSERT INTO "announcer" (team_id, display_name, nickname) VALUES (17, 'John Keating', '#IMWITHKEATS');
ALTER TABLE "pick" ADD COLUMN announcer_id BIGINT;
ALTER TABLE "pick" ALTER COLUMN user_id DROP NOT NULL;
CREATE TABLE "password_reset" (id SERIAL PRIMARY KEY, user_id BIGINT NOT NULL, reset_uuid VARCHAR(36) NOT NULL, create_time TIMESTAMP NOT NULL);