micronaut:
  server:
    cors:
      single-header: true
      enabled: true
    configurations:
      ui:
        allowed-origins:
          - http://127.0.0.1:63342
  security:
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "thisarealgoodsecretgeneratorsecret"
---
flyway:
  datasources:
    flywaysrc:
      enabled: true
      locations:
        - classpath:prod
---
datasources:
  flywaysrc:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pass
---
r2dbc:
  datasources:
    default:
      url: r2dbc:postgresql://localhost:5432/postgres
      username: postgres
      password: pass
      options:
        driver: pool
        protocol: postgresql
        maxSize: 80
#---
#logger:
#  levels:
#    io.r2dbc: TRACE
#    io.micronaut.data: TRACE
---
credential.path: /home/jgray1206/credentials.json
token.path: /home/jgray1206/tokens