micronaut:
  server:
    cors:
      single-header: true
      enabled: true
    configurations:
      ui:
        allowed-origins:
          - http://127.0.0.1:63342
  security:
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "${random.uuid}"
---
flyway:
  datasources:
    flywaysrc:
      enabled: true
      locations:
        - classpath:prod
---
datasources:
  flywaysrc:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pass
---
r2dbc:
  datasources:
    default:
      dialect: H2
      url: r2dbc:postgresql://localhost:5432/postgres
      username: postgres
      password: pass
---
logger:
  levels:
    io.r2dbc.h2: DEBUG
---
credential.path: ${HOMEPATH}\credentials.json
token.path: ${HOMEPATH}\tokens