micronaut:
  application:
    name: light-the-lamp
  security:
    authentication: cookie
    redirect:
      login-failure: /login/authFailed
    token:
      jwt:
        generator:
          access-token:
            expiration: 14400
        signatures:
          secret:
            generator:
              secret: "${JWT_GENERATOR_SIGNATURE_SECRET}"
---
flyway:
  datasources:
    flywaysrc:
      enabled: true
      locations:
        - classpath:prod
datasources:
  flywaysrc:
    url: jdbc:postgresql://localhost:5432/lightthelamp
    username: ${DB_USER:}
    password: ${DB_PASS:}
---
r2dbc:
  datasources:
    default:
      dialect: H2
      url: r2dbc:postgresql://localhost:5432/lightthelamp
      username: ${DB_USER:}
      password: ${DB_PASS:}
---
netty:
  default:
    allocator:
      max-order: 3
---
openapi-micronaut-client-base-path: https://statsapi.web.nhl.com/api/v1/
---
logger:
  levels:
    io.r2dbc.h2: INFO
---
resilience4j:
  ratelimiter:
    enabled: true
    configs:
      default:
        limitForPeriod: 1
        limitRefreshPeriod: 1s
        timeoutDuration: 1s
        eventConsumerBufferSize: 20
    instances:
      usercreate:
        baseConfig: default