CREATE SCHEMA IF NOT EXISTS dbo;
SET SCHEMA dbo;
CREATE TABLE "user" (id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, email VARCHAR(50), password VARCHAR(120));
CREATE TABLE "group" (id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, team_id SMALLINT, name VARCHAR(128));
CREATE TABLE "user_group" (id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, "user_id" BIGINT, "group_id" BIGINT);